name: Lint and Publish OpenAPI Specification

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint OpenAPI Specification
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install openapi-cli
      run: npm install -g @redocly/openapi-cli

    - name: Lint OpenAPI Spec
      run: openapi lint openapi.yaml

  publish:
    name: Publish OpenAPI Specification
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install redoc-cli
      run: npm install -g redoc-cli

    - name: Generate HTML Documentation
      run: redoc-cli bundle openapi.yaml -o public/index.html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1